version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "oteb-api"
s3_bucket = "oteb"
s3_prefix = ""
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
