AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: OTEB API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Runtime: nodejs14.x
    Environment:
      Variables:
        TABLE_NAME: !Ref Table
    Architectures:
      - x86_64

Resources:
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: userId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  WelcomeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 3
      CodeUri: welcome/
      Handler: app.lambdaHandler
      Events:
        Welcome:
          Type: Api
          Properties:
            Path: /
            Method: get

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: create-user.lambdaHandler
      Policies: AmazonDynamoDBFullAccess
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user
            Method: post

  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: create-user.lambdaHandler
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: get

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: update-user.lambdaHandler
      Policies: AmazonDynamoDBFullAccess
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: put

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user/
      Handler: delete-user.lambdaHandler
      Policies: AmazonDynamoDBFullAccess
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: delete

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WelcomeApi:
    Description: "API Gateway endpoint URL for Prod stage for Welcome Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WelcomeFunction:
    Description: "Welcome Lambda Function ARN"
    Value: !GetAtt WelcomeFunction.Arn
  WelcomeFunctionIamRole:
    Description: "Implicit IAM Role created for Welcome Function"
    Value: !GetAtt WelcomeFunctionRole.Arn
